### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by luisantonioig**
Need more help to use this program

### CODE REVIEW

**Comment by bytbox** [comment]
Thanks, but no thanks. These instructions are on the order of "how to compile a go project", and we don't need every go project to re-write such instructions.

**Comment by luisantonioig** [comment]
Can I help in anything, I want contribute

**Comment by bytbox** [comment]
Hmm, I'm not sure. There really aren't a lot of features needed by `sloc`, and without any outstanding bugs, there's really no work I can think of that ought to be done. Perhaps adding support for more programming languages, if there's any you care about that aren't covered. (I never made any effort to make the list truly comprehensive -- it's basically just a list of the ones I've used :P ).

Now, if you really want, there are some natural ways to build on sloc (particularly the reposloc script, which could have features for tracking contributions by different people or whatever). But this is lonely work -- I'm otherwise occupied, so I wouldn't be able to help very actively. If you're looking to get long-term involved in your first open source project, this might not be the one.

**Comment by bytbox** [comment]
Oh, that's another thing to bear in mind. This repository isn't the most up-to-date version. See http://git.bytbox.net/sloc/. (That's where the reposloc script is.)

**Pull request closed without merging**
